apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ConfigMap.yaml
  - PersistentVolumeClaim.yaml
  - mongo-persistent-volume.yaml
  - Secret.yaml
  - mongo-service.yaml
  - StatefulSet.yaml
  - StorageClass.yaml